// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdaFEHP-AwJKB-6sZmazyGGoi8B2Hn7R0',
    appId: '1:1065007702272:web:ebc9ba106e740aa95f13e5',
    messagingSenderId: '1065007702272',
    projectId: 'bep-thong-minh-hoang',
    authDomain: 'bep-thong-minh-hoang.firebaseapp.com',
    storageBucket: 'bep-thong-minh-hoang.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ZSPsUqkok1_FbUu8U64NYwpoDo4dnj8',
    appId: '1:1065007702272:android:d92b7347139d45c45f13e5',
    messagingSenderId: '1065007702272',
    projectId: 'bep-thong-minh-hoang',
    storageBucket: 'bep-thong-minh-hoang.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdaFEHP-AwJKB-6sZmazyGGoi8B2Hn7R0',
    appId: '1:1065007702272:web:9e30efbd48d23da75f13e5',
    messagingSenderId: '1065007702272',
    projectId: 'bep-thong-minh-hoang',
    authDomain: 'bep-thong-minh-hoang.firebaseapp.com',
    storageBucket: 'bep-thong-minh-hoang.firebasestorage.app',
  );
}
